### ISSUE TITLE
duration attribute in the canonical job spec

### ISSUE THREAD

**Issue by dongahn** [flux-framework/rfc#100]
@morrone: I am working on a time-related scheduling logic which makes use of attributes like duration, start time, etc in my resource query work. Currently, jobspec has "duration" attribute whose value must be a string and one exampled used is "1 hour." As such, it doesn't require a certain format. It would make my life easier if the allowed time format is specified as part of this spec. Did you have thoughts on this?

**Comment by morrone** [comment]
I don't know...maybe we would do something fairly strict like ISO 8601 (e.g.  P1H15M) in the jobspec, and leave more english-language-like strings (e.g. 1 hour 15 minutes) to other interfaces?

Doesn't matter to me too much.  If we adopt a string format that isn't already specified elsewhere, we might just make new date/time/duration RFC and refer to that from our RFC 14.

**Comment by dongahn** [comment]
Yeah, I like the idea of using a stricter standard for the jobspec and leave more user-friendly time idioms to other interfaces. It seems piggybacking on a well-known standard like ISO 8601 has benefits, as presumably there are standard time converting functions that can convert ISO 8601 compliant format into the scheduling unit (e.g., second).

**Comment by SteVwonder** [comment]
Per a discussion in #189, we decided to make `duration` a floating-point number of seconds.
