### ISSUE TITLE
rfc14, problems with "at least" wording in examples

### ISSUE THREAD

**Issue by morrone** [flux-framework/rfc#105]
There is a problem with the wording "at least" in some of the rfc14 jobspec examples.  Here is one such case:

> Request 4 nodes with at least 2 sockets each, and 4 cores per socket

Note that in the jobspec, we are actually requesting _exactly_ 2 sockets:

```
    version: 1
    resources:
      - type: slot
        count: 4
        label: nodelevel
        with:
        - type: node
          count: 1
          with:
            - type: socket
              count: 2
              with:
                - type: core
                  count: 4
    tasks:
      - command: [ "flux", "start" ]
        slot: nodelevel
        count:
          per_slot: 1
    attributes:
      system:
        duration: 1 hour
 ```

The scheduler is expected, I think, to allocate whole nodes to each task.  Except that we have asked for nodes with _exactly_ 2 sockets, and each socket must have _exactly_ 4 cores.

So we can improve the example by changing the socket count section to, for instance, the following:

```
  - type: socket
    count:
        min: 2
        max: 10000000000
        operator: "+"
        operand: 1
```

But it is a bit clunky to make people guess a big enough number for "max".  We could perhaps introduce words like "INFINITY":

```
  - type: socket
    count:
        min: 2
        max: INFINITY
        operator: "+"
        operand: 1
```

But it would probably be nicer still to make field optional, so we can specify it like this:

```
  - type: socket
    count:
        min: 2
```

**Comment by grondo** [comment]
I think at one point we had implied that `count: N` was equivalent to `min: N` but the document now clearly says that count is a "fixed count" so you are correct.

What if `max: 0` or unset is defined as infinite? This is somewhat common practice (0 means unlimited) therefore it might not cause surprise and still allows these values to be numbers instead of numbers or special infinity value. It also allows the field to be optional if 0 is default, but I leave it for others to decide if "canonical" jobspec could have default values. (I go back and forth on this myself)

**Comment by morrone** [comment]
> I think at one point we had implied that count: N was equivalent to min: N but the document now clearly says that count is a "fixed count" so you are correct.

Yes, that had problems of its own because one would never know how many things they would get.  Usually when a person asks for 50 nodes, they want 50 not 73.  So in that case we don't want a lone count of "50" to mean "50 or more", we really want it to mean "just 50".

> What if max: 0 or unset is defined as infinite?

Using a special value like 0 would be fine as an internal implementation detail, but I think this interface is public and important enough to make it even cleaner.

As to default values, we already have those in the form of "exclusive".  There may be others.

**Comment by dongahn** [comment]
> The scheduler is expected, I think, to allocate whole nodes to each task. Except that we have asked for nodes with exactly 2 sockets, and each socket must have exactly 4 cores.

Does this mean, if the node has more cores, it won't be matched?

If you want to contain the tasks to a subset of cores on each node and yet still want to allocate the whole node exclusively (e.g., memory-bound MPI program only wants to run on a subset of cores to reduce memory pressure), how would you express it?

**Comment by dongahn** [comment]
>> The scheduler is expected, I think, to allocate whole nodes to each task. Except that we have asked for nodes with exactly 2 sockets, and each socket must have exactly 4 cores.

> Does this mean, if the node has more cores, it won't be matched?

Reading your post once again, this probably wasn't what you meant. This can be confusing because depending on whose perspective you describe this, both "exactly" and "at least" can be used. From the resource requirement point of view, this example describes "exactly" 4 cores. But from the scheduler's point of view, if a resource has at least that much quantity, it meets the requirement so matched.

For this particular example, i agree using `min:` makes more sense. But INFINITY or 0 probably won't be needed? If min is specified without 'max', it should imply all available already. IOW, the schulder will match this with all of the available...

**Comment by morrone** [comment]
> Does this mean, if the node has more cores, it won't be matched?

I realize that isn't what we want.  I am just trying to resolve some ambiguity in the specification (or maybe just in my current level of understanding).

So lets consider the case that you suggest: The "node" is under the slot, so it is assumed to be "exclusive".  That exclusivity tells the scheduler to schedule _whole_ nodes to the jobs, not just parts.

It then sees further requirements below the node. It asks for exactly two sockets and exactly 4 cores under each socket.  So if we have a node that has 4 sockets, and 8 cores per socket, I totally understand how that would meet the jobspec's request.  But now, what does the scheduler actually generate in the resource assignment document that it generates?

Does the resource assignment say "node foo, but only these two sockets, and only these four cores in each socket"?  That makes sense to me.  Then the flux component that creates the process container on that node knows what subset to use to match the jobspec's request.

More-or-less, we have used containers to supply exactly what the jobspec requested by using a larger node and containing the processes to only the requested number of sub-node components.

The scheduler, I assume, needs to keep a note internally that the _entire_ node is now allocated, even though the resource assignment only listed parts of the node as part of the job.

Is that how we expect it to work?

And then if the user really wanted the entire node's resources in the container, then would need to add a "min" count to the node's subcomponents (socket and core).

**Comment by grondo** [comment]
> Does the resource assignment say "node foo, but only these two sockets, and only these four cores in each socket"? That makes sense to me. Then the flux component that creates the process container on that node knows what subset to use to match the jobspec's request.

The slot is a *node* not  `2 * (socket * (4 cores))`, so it doesn't seem obvious to me that the container would include *only* the 2 sockets and 4 cores on each node, even if the node had 4 sockets with 8 cores per socket.

In the case a user wanted the slot to be 2  sockets with 4 cores on each socket then they should have defined the slot as such. There needs to be a way in the jobspec to be specific about the difference between "I want 10 nodes and they must each have at least 2 sockets with 4 cores each", and "I want 2 sockets with 4 cores per socket across 10 nodes". In the former case the container is the whole node, in the second case the container is 2 sockets with 4 cores on each socket.

Not that I'm saying I have a good idea about how to express this difference...

**Comment by dongahn** [comment]
@grondo and @morrone:

Yes, as I was thinking about this last Friday, I realized there are ambiguities in the current jobspec, which needs to resolved  1) through clearer documentation on the semantics, and 2) probably through some additional idioms. In addition, I thought we need to factor this into the future "R" format design. 

Maybe, we can try to express the following cases (and some more),  to bring some more clarity. 

1) Do we want to allow users to express "I want a resource exclusively whose sub-shape is exactly like this and that"? Like, I want a node exclusively, which contains exactly 2 sockets each with exactly 8 cores. If the scheduler see a node w/ more sockets and cores, it won't be matched. There is a philosophical question as to why we allow users to express something like this. But if we were, how would you suggest users to express this? What should R emitted by the scheduler look like.

2) I want exactly 1 socket each with 8 cores (exclusively) across 4 nodes but nodes can be shared? In this case, I want a node 2 sockets each with 16 cores meet this requirement. What should "R" look like? 

3)  I want exactly 1 socket each with 8 cores (exclusively) across 4 nodes but the nodes must be exclusive as well? What should "R" look like?

**Comment by morrone** [comment]
> The slot is a node not 2 * (socket * (4 cores)), so it doesn't seem obvious to me that the container would include only the 2 sockets and 4 cores on each node, even if the node had 4 sockets with 8 cores per socket.

Well, in order to take that intrepretation we perhaps need to make the scheduelr call the example that I gave an error.  Instead the user should have said "a minimum of 2 sockets" and each with "a minumum of 4 cores".  If we take the approach, then I have no argument.

In other words, if our cluster only has nodes with 4 sockets and 8 cores per socket, then this would trigger and error from the scheduler:

```
    version: 1
    resources:
      - type: slot
        count: 4
        label: nodelevel
        with:
        - type: node
          count: 1
          with:
            - type: socket
              count: 2
              with:
                - type: core
                  count: 4
    tasks:
      - command: [ "flux", "start" ]
        slot: nodelevel
        count:
          per_slot: 1
    attributes:
      system:
        duration: 1 hour
```

But this would be fine (and each slot contains only 8 total cores evenly spread across two sockets):

```
    version: 1
    resources:
      - type: node
        count: 4
        with:
        - type: slotlevel
          count: 1
          with:
            - type: socket
              count: 2
              with:
                - type: core
                  count: 4
    tasks:
      - command: [ "flux", "start" ]
        slot: slotlevel
        count:
          per_slot: 1
    attributes:
      system:
        duration: 1 hour
```

And this would also be a valid request (and each slot container contains _all_ sockets and cores on the node):

```
    version: 1
    resources:
      - type: slot
        count: 4
        label: nodelevel
        with:
        - type: node
          count: 1
          with:
            - type: socket
              count:
                min: 2
              with:
                - type: core
                  count:
                    min: 4
    tasks:
      - command: [ "flux", "start" ]
        slot: nodelevel
        count:
          per_slot: 1
    attributes:
      system:
        duration: 1 hour
```

**Comment by grondo** [comment]
@morrone, that seems reasonable to me -- kind of like greedy vs non-greedy matching.

However, I wonder if by applying some kind of new keyword or label, could the intent between these different cases be made even clearer?

**Comment by grondo** [comment]
> Do we want to allow users to express "I want a resource exclusively whose sub-shape is exactly like this and that"? Like, I want a node exclusively, which contains exactly 2 sockets each with exactly 8 cores. If the scheduler see a node w/ more sockets and cores, it won't be matched. There is a philosophical question as to why we allow users to express something like this.

Your example case may cause a philosophical crisis :smile:, but I can imagine other more general cases where we *do* want allow a request that matches a subtree/subgraph with a certain shape, especially since the resource model is generic, and matching of this type may apply to resources above and/or below the level of "node" in the hierarchy.

> But if we were, how would you suggest users to express this? What should R emitted by the scheduler look like.

I think @morrone probably showed above how it would be expressed in canonical jobspec (how the users actually specify it might be something different). When converting from user input to jobspec, there might be some rules about when to use `min` and when to use `count`.

Regarding the form of `R`, would it help to think about `R` as sufficient input to resource database to create a new instance on the assigned resources? For example, an `R` for the exclusive node case would contain data for all the resources on the node (and its parents back up to the root if possible), and for the non-exclusive case, `R` would contain the node with only the allocated 2 sockets each with 8 cores. In effect, to a new resource database the node would appear like it only had 2 sockets with 8 cores each.

**Comment by dongahn** [comment]
How about this? My 3rd case:

```yaml
    version: 1
    resources:
      - type: node
        count: 4
        exclusive: true
        with:
        - type: slot
          count: 1
          label: slotlevel
          with:
            - type: socket
              count: 2
              with:
                - type: core
                  count: 4
    tasks:
      - command: [ "memory-BW-intensive"]
        slot: slotlevel
        count:
          per_slot: 1
    attributes:
      system:
        duration: 1 hour

```

**Comment by grondo** [comment]
> How about this? My 3rd case:

This is where I think the `exclusive` keyword (or some similar flag) would be very useful. To me, this clearly says that the user wants 4 whole nodes that must have at least 2 sockets, each with 4 cores.
This solves the ambiguity of what the slots are *exactly* when you want a minimum count of some sub-resource in the graph/hierarchy. 

`R` would include all allocated resources, which is the whole node, However, the execution subsystem would run the `memory-BW-intensive` tasks such that they are each bound to 2 sockets/4 cores-per-socket (either via containers or by  cpu-affinity/membind -- mechanism doesn't matter).

Hope that makes some sense, and remember it is only my opinion/interpretation and is certainly up for debate.

**Comment by dongahn** [comment]
>  the execution subsystem would run the memory-BW-intensive tasks such that they are each bound to 2 sockets/4 cores-per-socket (either via containers or by cpu-affinity/membind -- mechanism doesn't matter).

Just for an argument sake, if the execution system will contain/bind the tasks to only the subset of the node resource, I am wondering why it would need the whole node resource info? 

Also, if we go with this interpretation, don't we also need the emitted R contain the slot info as well? 

What is the best sockets/cores (or any types of generic resources) to contain/bind your execution can only be known by the scheduler according to its resource matching policy; so it seems the concretized slot info needs to be embedded into the R being emitted...

Just my $0.02.

**Comment by grondo** [comment]
> Just for an argument sake, if the execution system will contain/bind the tasks to only the subset of the node resource, I am wondering why it would need the whole node resource info?

It seems less surprising and perhaps less work to define that *R* always contains all allocated resources. The execution subsystem may not need the extra information, but this way we separate the concerns of  the service doing the allocation from the thing using the allocation. If the launched tasks make up a new instance for example, that instance will want all allocated resources in `R` as input to the newly instantiated resource service.

> Also, if we go with this interpretation, don't we also need the emitted R contain the slot info as well?

> What is the best sockets/cores (or any types of generic resources) to contain/bind your execution can only be known by the scheduler according to its resource matching policy; so it seems the concretized slot info needs to be embedded into the R being emitted...

You might be right, though I had never thought of this way. But the scheduler has already done the work to match slots to resource sets, so if there is a way to emit slot annotations in *R* that could be very useful for the execution service. In fact in a complex, multi-slot jobspec it might be essential.

**Comment by dongahn** [comment]
> If the launched tasks make up a new instance for example, that instance will want all allocated resources in R as input to the newly instantiated resource service.

Yeah, I was going back and forth on this myself as well. In fact, parent-child resource-set coordination probably is one area for which we will need to pencil in a clear semantics somewhere. 

My current thinking is: I look at `slot` as resource containment info. If the upper-level instance contains the program to a subset of the resources, one might argue the lower-level flux instance should also be contained in that resource set. 

This may be the baseline semantics, but maybe we can introduce a way to override this for further optimization later.


> You might be right, though I had never thought of this way. But the scheduler has already done the work to match slots to resource sets, so if there is a way to emit slot annotations in R that could be very useful for the execution service. In fact in a complex, multi-slot jobspec it might be essential.

Good feedback. I will try to encode slot into R and make two emitting options: 1) generate the full info from the top exclusive level downward; 2) the alternative (emitting only the subset). These would be useful for further evaluation. 

This leaves one remaining question for me -- which is 1). Maybe, we don't allow exact match like that for now. (philosophical crisis ;-). If we see killer use cases later down the road, we may need to introduce a slight revision to jobspec to enable it.

@morrone: Does this work for you?

**Comment by morrone** [comment]
>> How about this? My 3rd case:

> This is where I think the exclusive keyword (or some similar flag) would be very useful. To me, this clearly says that the user wants 4 whole nodes that must have at least 2 sockets, each with 4 cores.

But it doesn't say that.  It says exactly 4 nodes, each with exactly 2 sockets, each with exactly 4 cores.  Changing nodes to "exclusive" doesn't automatically change counts into being minimums.  If it did, then they were _already_ minimums, because everything under a slot is already specified to be "exclusive".

> My current thinking is: I look at slot as resource containment info.

I'm not entirely clear that matches what we currently have.  But then, it may also depend on exactly your interpretation of "contaiment info".  In one manner of thinking, the entire _R_ is containment info.

Slots are primarily a way to map tasks onto the assigned resources.

**Comment by grondo** [comment]
> But it doesn't say that. It says exactly 4 nodes, each with exactly 2 sockets, each with exactly 4 cores. Changing nodes to "exclusive" doesn't automatically change counts into being minimums. If it did, then they were already minimums, because everything under a slot is already specified to be "exclusive".

Because you request 2 sockets, it doesn't mean the node can't have 4 sockets does it? If that were the case, then if I ask for 4 nodes on a cluster, that would mean I want a cluster with *exactly* 4 nodes?

I think the scheduler or resource matcher would first match the resources that are actually in the request. If the "exclusive" (or whatever) keyword is not there, then you get only the matching sufficient resources. If scheduler finds the "exclusive" keyword, then it gives you the entire thing that you wanted exclusively.

Like I said, I like this because it is a more explicit way to differentiate a request where a user wants *exactly* these resources from one where a user wants a resource that has a certain shape (but they want all of that thing)

Now I also admit I haven't done a deep dive on this, especially into what is possible with the jobspec itself, so your (and @dongahn's) opinions may have slightly more weight than mine.

**Comment by dongahn** [comment]
> I'm not entirely clear that matches what we currently have. But then, it may also depend on exactly your interpretation of "contaiment info". In one manner of thinking, the entire R is containment info.

> Slots are primarily a way to map tasks onto the assigned resources.

True. I meant  "contaiment info" generically. The resource set visible to the substance. -- so the entire R that is passed to the instance.

**Comment by dongahn** [comment]
> But it doesn't say that. It says exactly 4 nodes, each with exactly 2 sockets, each with exactly 4 cores. Changing nodes to "exclusive" doesn't automatically change counts into being minimums. If it did, then they were already minimums, because everything under a slot is already specified to be "exclusive".

Yeah, this was why I was interpreting this to emit only the best matching 2 sockets and 4 cores each...

**Comment by grondo** [comment]
> But it doesn't say that. It says exactly 4 nodes, each with exactly 2 sockets, each with exactly 4 cores. Changing nodes to "exclusive" doesn't automatically change counts into being minimums. If it did, then they were already minimums, because everything under a slot is already specified to be "exclusive".

I think I'm still confused. If someone made that same request, without exclusive, couldn't the 2 sockets with 4 cores each be allocated from *shared* nodes that have 4 sockets with 8 cores each, leaving 4 cores on each socket, and 2 full sockets free? Are you actually saying that "exclusive" implies that everything below it must be an exact match?

**Comment by dongahn** [comment]
I think I understand what @morrone is saying. 

This user specified that she needs exactly 2 sockets and 4 cores each. Not a min of 2 sockets and 4 cores. If it were "min", the scheduler will give all available from our last discussion and your semantics, @grondo, makes a perfect sense. 

But @morrone is saying "exclusive" at a higher level should not change this semantics of this "exact count" specification. (Not to be confused with "matching of the exact resource").

From the scheduler's point of view, a node with 4 sockets with 8 cores will satisfy this request. But @morrone may want to see only the matched sockets and cores in the R.

**Comment by grondo** [comment]
> From the scheduler's point of view, a node with 4 sockets with 8 cores will satisfy this request. But @morrone may want to see only the matched sockets and cores in the R.

OK, I think I see now, thanks. I'm not sure that I agree, but basically exclusive works the same as a request without exclusive, except it adds an extra constraint that the resource at the level that "exclusive"  is used (and all its children) can't be currently allocated, nor will they be allocated until the job is released. However, the R generated is the exact match as you said.

My intuition is that this case won't be useful, and in 99% of cases what the user will want is to use `min` and not `count` (and perhaps this is what @morrone has been arguing all along) You've also created a case where resources have essentially been allocated to a job, but can't be used by the job since they were not granted in *R*, so that is some new resource state to track (perhaps not a big issue for the proposed implementation, though)

Hm, even for the `min` case, is it not a guarantee that all the resources on the exclusive node would appear in *R*, since this depends on if the scheduler does greedy vs non-greedy matching?

**Comment by dongahn** [comment]
For 99% percentage of the *current* use, the users would specify `min:` in this case. But having ways to specify exact specification can address the other 1% and other future cases?

> Hm, even for the min case, is it not a guarantee that all the resources on the exclusive node would appear in R, since this depends on if the scheduler does greedy vs non-greedy matching?

I think this would be manageable as far as we are consistent with our R emitting rules and options. Maybe the baseline rules can be something like:

Every resource at the subtree of an exclusive resource will be emitted unless this is overridden through further exclusivity specialization using exact counts... 

We would also need some rules and options so that those resources that are only associated with the containment hierarchy (but not part of -- e.g., power hierarchy), can also be emitted.

**Comment by grondo** [comment]
@dongahn, yes I can see your point. As long as we are consistent I agree.

> We would also need some rules and options so that those resources that are only associated with the containment hierarchy (but not part of -- e.g., power hierarchy), can also be emitted.

Also consider whether some resources up to the root may need to be emitted as well. This includes locality and other important information in the emitted *R*. (Sorry if this was obvious)

**Comment by dongahn** [comment]
Yeah. I believe R should be a complete resource set that can enable various policies of the child scheduler instance's (simple to complex). But then, since the parent may want to control the level and kinds of the children policies, we would need some support for multilevel emit options... I am sure we will revisit this topic.

**Comment by morrone** [comment]
> What is the best sockets/cores (or any types of generic resources) to contain/bind your execution can only be known by the scheduler according to its resource matching policy; so it seems the concretized slot info needs to be embedded into the R being emitted...

I'm not sure that I understand that argument.  R contains the allocated resources that meet the requirements set in the jobspec.  Do we think we will be unable to compare the resouce section of the jobspec to the resources listed in R and algorithmically determine the correct mapping?

Because if we can't, then we might have problems in the security arena if we can't validate that the resource in R match what was requested in J.  And if we _can_ then we can get the slot information in J, and slot information to R's resource list will only add complexity.

I'm hoping slots will not appear outside of J.  If they are duplicated elsewhere, I think we are opening a new can of worms.

**Comment by dongahn** [comment]
>> What is the best sockets/cores (or any types of generic resources) to contain/bind your execution can only be known by the scheduler according to its resource matching policy; so it seems the concretized slot info needs to be embedded into the R being emitted...

> I'm not sure that I understand that argument. R contains the allocated resources that meet the requirements set in the jobspec. Do we think we will be unable to compare the resouce section of the jobspec to the resources listed in R and algorithmically determine the correct mapping?

If we interpret the "exact count" of a resource differently across when it is under an exclusive resource  or not, then the answer would be no.  

Because the scheduler only knows what's the best matching according to its selection policy, but not the execution service, the slot information needs to be there in the R. 

But if the semantics of the "exact count" is always consistent, the slot info doesn't need to be there, provided that the execution service engine wants to do the slot mapping by itself.

First thing that we all need to  agree is, though, the exact semantics of "exact count" specification.  @grondo and I seemed to converge to "non-greedy" interpretation. Do you? (it seems from your previous postings).

I can always emit R with or w/o slot. This is not a problem. We probably want to evaluate this when the execution service code starts to grow.

**Comment by grondo** [comment]
> I'm not sure that I understand that argument. R contains the allocated resources that meet the requirements set in the jobspec. Do we think we will be unable to compare the resouce section of the jobspec to the resources listed in R and algorithmically determine the correct mapping?

> Because if we can't, then we might have problems in the security arena if we can't validate that the resource in R match what was requested in J. And if we can then we can get the slot information in J, and adding slot information to R's resource list will only add complexity.

I think this is a good observation, however are we really adding complexity by annotating the slots in R? In fact, if the execution system or task mapping service is required to rediscover slots within R, isn't it just re-doing the work the scheduler has already done? (I'm not saying it isn't possible, but why re-do the same work in 2 subsystems?). So perhaps some complexity is added to the representation of R, but complexity of the default task mapper is reduced?

One thing to keep in mind, though, is that the scheduler should not have to know *everything* about task mapping. We want sites and users to be able to add custom task mappers, and not have to write a scheduler extension to do so.

**Comment by dongahn** [comment]
> One thing to keep in mind, though, is that the scheduler should not have to know everything about task mapping. We want sites and users to be able to add custom task mappers, and not have to write a scheduler extension to do so.

I completely agree. The scheduler should only concern best-matching resource selection. It should not even crack open the tasks section.

**Comment by grondo** [comment]
> Perhaps that addition isn't really that major. But since we have to do the validation mapping between J and R anyway, I'm not sure that adding the slot information to R buys us anything.

I wasn't assuming that slot information would be used to validate that R matches the resources in J. I guess the shape of slots multiplied by the number of each slot requested does form the aggregate request, however, ensuring the request is met in the aggregate doesn't require that you map where each slot is within the hierarchy of R.

Also, the IMP is a separate process from whatever is doing the mapping, so there would be no purpose for it determine the actual location of any slots.

That being said I'm just thinking theoretically at this point and you and @dongahn are putting theory to practice so you have more insight than I do here.

**Comment by morrone** [comment]
> Also, the IMP is a separate process from whatever is doing the mapping, so there would be no purpose for it determine the actual location of any slots.

The IMP is responsible for creating the linux containers into which the flux job shell is launched, correct?  I'm not sure how the IMP can a) figure out if if should obey R's signer and run the job shell as the signer of J unless it validates that R's resource designation really matches what is written in J, and b) figure out what the linux containers should look like without knowing the groupings introduced by slots.

When I said "mapping", I was not talking about task layout.  I was talking about figuring out how the abstract resource resquest in J corresponds to the real resources allocated in R, and validating that there is a direct, correct correlation between the two.

**Comment by grondo** [comment]
> When I said "mapping", I was not talking about task layout. I was talking about figuring out how the abstract resource resquest in J corresponds to the real resources allocated in R, and validating that there is a direct, correct correlation between the two.

Ah, ok. That makes sense.

> The IMP is responsible for creating the linux containers into which the flux job shell is launched, correct? I'm not sure how the IMP can a) figure out if if should obey R's signer and run the job shell as the signer of J unless it validates that R's resource designation really matches what is written in J, and b) figure out what the linux containers should look like without knowing the groupings introduced by slots.

Yes, you are correct that the IMP will create or add processes to the container for the job shell.

I definitely agree with your (a) above, but I'm not sure that you need the groupings of slots to create a container as you say in (b). The container can be obtained (in theory) by taking the intersection of the current container in which the IMP is running when it is launched with the resource set in R.

**Comment by morrone** [comment]
> The container can be obtained (in theory) by taking the intersection of the current container in which the IMP is running when it is launched with the resource set in R.

Correct me if I'm wrong, but you seem to be making an assumption there that there will only ever be a single container per node.  Is that the model we want to enforce?  Consider this excerpt from a jobspec, and assume a cluster with nodes each having 16 cores:

```
resources:
  type: slot
  count: 64
  label: foo
  with:
    type: core
    count: 4
```

This request doesn't care about nodes.  It just cares that each slot use 4 cores.  So since nodes have 16 cores, the scheduler might decide to use only 4 nodes to satisfy this request, putting 4 slots on each node.  Lets assume that is the case.

Now there are a few possibilities of what happens next:
1) The broker on each node starts 4 IMPs, which each create one linux container on the correct 4 cores
2) The broker on each node starts 1 IMP, which creates 4 linux containers, each with 4 cores.
3) The broker on each node starts 1 IMP, which creates 1 linux container of all 16 cores.

It seems like you are assuming option 3.  If that is the case (and assuming 1 task per slot), how does the flux job shell launch the 4 tasks?  Are they simply started on the same node with no further isolation?  (I'm not saying that is wrong, I'm just trying to get the details straight in my mind.)

**Comment by grondo** [comment]
>  If that is the case (and assuming 1 task per slot), how does the flux job shell launch the 4 tasks? Are they simply started on the same node with no further isolation? (I'm not saying that is wrong, I'm just trying to get the details straight in my mind.)

You are correct, I have been assuming approach 3. The shell will be capable of further isolation within the resources in its container using cpu affinity, membind, or perhaps even other container strategies if the linux containers can still be "chown"ed to the guest running the shell.

Once this strategy works, 2 could be implemented with optional behavior in the IMP. I think in this case the easiest thing to do would be to start 4 shells, 1 per container (I'm not sure how a single shell would create multiple tasks in different containers without privilege, though it may be possible.)

I can't see a strong argument for a case where we start multiple IMPs per node (or more generally on the "maximum resource vertex that supports execution" (what is the correct graph term for that?)), it seems like we'd want to minimize the number of these we have to run.

Same with any job shell -- it seems like minimizing the number of job shells you have to run per job is a scalability win, as long as the shell itself is able to launch its processes 1 to N quickly and scalably.

**Comment by SteVwonder** [comment]
After psuedo-randomly stumbling on this thread, I wanted to clarify something.

I agree with Chris's analysis in [this comment](https://github.com/flux-framework/rfc/issues/105#issuecomment-330323081). Basically, if a user requests an exclusive node with exactly 4 cores, then the R that is emitted by the scheduler should only include 4 cores.  If all the nodes in the cluster are fatter than 4 cores, then the remaining cores on the node are "lost" due to "fragmentation" (or some other more clever phrase like "overshadowing").  As an optimization, maybe we can add something to the scheduler or job shell that "reclaims" these "overshadowed" cores, but for now, I just want to clarify the intended behavior of the scheduler/canonical jobspec.

If the "overshadowing" is in-fact the intended behavior, then I think we should follow through with the action item proposed in the OP of this thread: remove the "at least" phrases from Use Case 1.3 (and maybe a few others).  We could also mention this "overshadowing" issue in the RFC and provide the examples above that leverage `min` on `cores` and `sockets` to elimiate the overshadowing.

**Comment by grondo** [comment]
FWIW, I agree -- Chris' initial suggestion makes the most sense. We should definitely remove the "at least" wording, and show a counter example using `min:` as Chris suggested. (and I also like his suggestion to make `max:` optional if we haven't already done so)

After rereading this thread, I forsee that default slot exclusivity is going to be a huge pitfall, especially applied to nodes. If we ever had a jobspec linter, I would want it to issue a warning if a slot is specified at the `node` level, without `min` being used for counts on child resources within the slot.

I'll also note that a couple of the suggestions to address #150 might help with the ambiguity here.

**Comment by SteVwonder** [comment]
> After rereading this thread, I forsee that default slot exclusivity is going to be a huge pitfall, especially applied to nodes. If we ever had a jobspec linter, I would want it to issue a warning if a slot is specified at the node level, without min being used for counts on child resources within the slot.

This is an excellent suggestion!

**Comment by dongahn** [comment]
@SteVwonder and @grondo: good discussion. 

I think we can still use "at least", though, as far as we define what we mean by that in the RFC 14.

 In our context, if a plain `count` key is used, the scheduler will use its value to see if its matching resource vertex has "at least" that quantity and then generate `R` that contains "exactly" that quantity. 

The reason we need a clear definition is that, without the use of "at least" we can easily misspeak that we do "exact match" which we really don't want. 

I don't think this is a big deal. This is just a matter of clear definitions and semantics.

**Comment by dongahn** [comment]
Yes, if users want the whole sub resources generated in the `R`, they will have to use `min`. The `max` should be the entire quantity. I have this already implemented in my resource matching service.
