### ISSUE TITLE
rfc3: ABNF grammar

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/rfc#120]
I have been re-reading older RFCs while working on #112. While digging through the ABNF grammar for CMB1 messages, I ran into three things that I couldn't quite reason out.

First, what do the `C` and the `S` in front of `request`, `response`, `event`, and `keepalive` mean?    I presume they stand for client and server, but I couldn't find them defined in [Wikipedia's ABNF page](https://en.wikipedia.org/wiki/Augmented_Backus%E2%80%93Naur_form).

----

Second, in the top definition,
```
CMB1		= C:request *S:response
		/ S:event
		/ C:keepalive
```
is the asterisk in front of `S:response` intentional?

----

Third, (which is more of a comment than a question) in both the grammar and the text there are references to a "zero-sized delimiter":
```
 If message identity parts are present, a zero-size route delimiter frame MUST be present and positioned next.
```
```
; Route frame stack, ZeroMQ DEALER-ROUTER format
routing		= *identity delimiter
identity	        = 1*OCTET		; socket identity ZeroMQ frame
delimiter	= 0OCTET		; empty delimiter ZeroMQ frame
```
Looking solely at the grammar, it wasn't clear to me what it means for a zero-sized frame to be present. Digging into the [flux-core code](https://github.com/flux-framework/flux-core/blob/fd68af2c62dac25068a28e53e7d400ca5b275b25/src/common/libflux/message.c#L723), I see that a call to [zmsg_pushmem](https://github.com/zeromq/czmq/blob/dd252dbf9ab345f401e468ec6a2d001ae5a344fc/src/zmsg.c#L304) with a size of 0 is called, which creates a `zframe` of size 0.  It all seems really clear in hindsight, but without digging into the actual code, I was left confused as to how a zero-sized object could be present and be positioned at all.  Wrapping this data in a `zframe` also makes clear how you can have an arbitrary number of identities of arbitrary size and still be able to disambiguate each identity.  I'm not really suggesting any changes with this third comment, but maybe this will help someone stuck where I was.

**Comment by garlick** [comment]
Thanks for  feedback!

The C and S represent "client" and "server".  I borrowed that notation from some 0mq documentation, though I should double check that it is valid ABNF and certainly document what that shorthand means.

> Is the asterisk in front of S:response intentional?

Yes, a request with the matchtag field set to `matchtag-none` does not require a response.

> there are references to a "zero-sized delimiter":

That clearly should have some reference to the ZMTP spec.

Sorry for the lack of clarity on these things!

**Comment by SteVwonder** [comment]
Thanks @garlick for the info!

> I should double check that it is valid ABNF

I'm pretty sure it is valid ABNF to have a `:` in a rule name.  So I think you are alright in that respect.

> Yes, a request with the matchtag field set to matchtag-none does not require a response.

So there can either be no response or one response, right (i.e., `0*1S:response`)?   What would multiple `S:response`s in the same CMB1 message look like?  Are they just concatenated together?

**Comment by garlick** [comment]
We do currently allow multiple responses to one request, for example in `kvs_watch()`.  Each time a key changes, a response is generated.  We also use it for stdio handling in hte cmb.exec service.  This is an area of the protocol that needs tightening up IMHO.

**Comment by garlick** [comment]
I kind of like this idea of Unary vs Streaming RPC's.  Maybe a "streaming" mode is what we need.

https://grpc.io/docs/guides/concepts.html

**Comment by SteVwonder** [comment]
So I was looking into how to use streaming RPCs and I found this in RFC 6:

> The server SHALL send zero or one responses to each request, as established by prior agreement between client and server (e.g. defined in their protocol specification).

So I guess RFC 6 needs to be updated the reflect the ability for multiple responses to be sent.

**Comment by garlick** [comment]
RFC 3 and RFC 6 have been updated to clarify that a request can have 0, 1, or multiple responses.

We should add something to explain what the C: and S: prefixes mean.

We should also add something to note that the ABNF does not describe messages in terms of the raw wire protocol, but in terms of ZeroMQ messages built up from message parts (frames).
