### ISSUE TITLE
new rfc: document FLUID design

### ISSUE THREAD

**Issue by garlick** [flux-framework/rfc#128]
@grondo did a nice job of laying out a proposal for Flux Locally Unique IDs (FLUIDs) in flux-framework/flux-core#470.  Since then, an implementation of a FLUID generator has been added to flux-core, and  flux-framework/flux-core#1543 proposes it as the basis for Flux jobid's.  If that design is accepted, we should consider translating the original proposal to an RFC here.

Possible changes needed to the design (still up in the air I think):
* Need save/restore capability for generators, flux-framework/flux-core#1545
* (maybe) need time portion better synchronized across FLUID id's (ranks) if degree of partial ordering of distributed FLUID generation is useful to discipline

**Comment by grondo** [comment]
> (maybe) need time portion better synchronized across FLUID id's (ranks) if degree of partial ordering of distributed FLUID generation is useful to discipline

A synchronized monotonic clock across Flux ranks sounds like it would be useful to other services (maybe even exported via the API for users?). Do we need to think about how to accomplish this in general, then make use of it in FLUID generators?

**Comment by garlick** [comment]
That's a good thought.  This is kind of along the lines of what the heartbeat is for.  Maybe we could implement/augment the heartbeat API to include the heartbeat period, time since last heartbeat (e.g. microsecond granularity), and time since first heartbeat?

It makes sense to me to have a heartbeat RFC since that was  fundamental design element.  I'll open another issue on that.
