### ISSUE TITLE
rfc14: use json-schema instead of json-content-rules

### ISSUE THREAD

**Issue by garlick** [flux-framework/rfc#142]
As discussed in flux-framework/flux-core#1714, json-schema has as an off-the-shelf validator for python (and other environments), while json-content-rules is more limited in that regard.

Let's translate the JCR in RFC 14 to json-schema since it has better prospects for actually being useful to us.

**Comment by garlick** [comment]
After flux-framework/flux-core#1913 is reviewed, we can pull the schema in here.

**Comment by dongahn** [comment]
@garlick: are you talking about https://json-schema.org?

The reason I am asking is I see JGF already has a validator w/ this. And if we were to go with JGF for `R`, there seems a good synergy including not having to pull in additional dependencies...

**Comment by dongahn** [comment]
Duh. I just looked at the PR 1913 and indeed this is the same json schema!
