### ISSUE TITLE
RFC14: make fails on quartz

### ISSUE THREAD

**Issue by dongahn** [flux-framework/rfc#156]
```
asciidoc -o spec_14.html spec_14.adoc
asciidoc: ERROR: spec_14.adoc: line 135: illegal style name: horizontal width=20%
asciidoc: ERROR: spec_14.adoc: line 141: illegal style name: horizontal width=30%
source-highlight: missing feature: language inference requires input file
source-highlight: could not find a language definition for yaml
asciidoc: WARNING: example1.yaml: line 19: filter non-zero exit code: source-highlight -f xhtml -s yaml: returned 1
asciidoc: WARNING: example1.yaml: line 19: no output from filter: source-highlight -f xhtml
```

**Comment by grondo** [comment]
Ah, yeah @SteVwonder caught this too and has a pending fix somewhere. My fault, sorry about that!

**Comment by SteVwonder** [comment]
> has a pending fix somewhere

It is in #154

**Comment by SteVwonder** [comment]
Mostly for my own future reference...to fix the source-highlight warning: https://gist.github.com/zeroyonichihachi/c4952b355bb7a27552a5f23e0c53b65f

**Comment by SteVwonder** [comment]
Looks like mergify also failed to close this issue 😢

**Comment by grondo** [comment]
Bah, the universe doesn't want us to have nice stuff! :sob:

I wonder if we can email GitHub support? Seems like a GitHub issue not Mergify, if I had to guess.

**Comment by dongahn** [comment]
Did we ever link that PR to this issue though? (Like having "Resolve Issue #156)?

**Comment by grondo** [comment]
Yes, it was mentioned in the [PR](https://github.com/flux-framework/rfc/pull/154).
I wonder if the Mergify integration needs to be given issue permissions. I don't see how to do that, maybe I'll try to email their support even though we don't have a subscription.
