### ISSUE TITLE
rfc20: allow multiple ranks per entry in R_lite

### ISSUE THREAD

**Issue by grondo** [flux-framework/rfc#161]
I'd like to extend the format of the `execution.R_lite` key in RFC 20 to allow a more compact representation of resource sets where many ranks have the same sets of resource identifiers allocated.

The gist is to allow either an alternate key `ranks` instead of `rank`, which will be a string encoding a set of ranks to which the current entry applies, or to allow the existing `rank` key in `R_lite` to be either an integer or a string. If `rank` is a string, then it must be a set of ranks in idset format.

Which would you prefer?

As an example, here's an *R* for a 1024 node cluster with 32 cores per node using the `ranks` key:

```json
{
  "execution": {
    "R_lite": [
      {
        "children": {
          "core": "0-31"
        },
        "ranks": "0-1023"
      }
    ]
  },
  "version": 1
```

**Comment by grondo** [comment]
In creating a test implementation of compact *R_lite*, I found it was much easier to change the `rank` key to  a string in idset format. This is much cleaner because the single entry per rank and multi-rank entries can be handled exactly the same. I'll propose a PR with an update to the RFC.

**Comment by dongahn** [comment]
@grondo:  Seems like a reasonable optimization. 

Two questions:

How does this affect the `node` key though? For this representation, `node` doesn't make a lot of sense. Maybe we should just make `node` optional as part of this revision?

Just playing a devil's advocate, if `R_lite` will have to go away in favor of an API approach in the future, do we need this optimization at this point though?

**Comment by grondo** [comment]
> node doesn't make a lot of sense. Maybe we should just make node optional as part of this revision?

Yes, that is what I'll do in my PR.

> Just playing a devil's advocate, if R_lite will have to go away in favor of an API approach in the future, do we need this optimization at this point though?

Using a compact format has many benefits in the near term (testing as well as manual inspection), and is trivial to implement at this time. Since we already have specified R_lite for now, this seems like a valid improvement for the time we're using that format.

**Comment by dongahn** [comment]
> Using a compact format has many benefits in the near term (testing as well as manual inspection), and is trivial to implement at this time. Since we already have specified R_lite for now, this seems like a valid improvement for the time we're using that format.

Fair enough. Like I said before, I thought this was a reasonable optimization but was wondering how much efforts needed and payoff. Since this is easy to implement, I am fine. Just to make sure that the current single-rank format is also valid. I don't know how much more complexity within the new emitter it will require to do additional compacting. Will surely discuss by the time I can get there: https://github.com/flux-framework/flux-sched/issues/445
