### ISSUE TITLE
rfc 14: allow attributes to have any value type

### ISSUE THREAD

**Issue by garlick** [flux-framework/rfc#172]
As noted in flux-framework/flux-core#2073 in the context of passing debug input to the exec system, RFC 14 JCR limits user and system attributes to strings only, but the textual description appears to allow a value to be any type.  I'm not sure if this was at one time a real requirement, or just an error.  It seems like allowing any JSON object is a powerful way for users to provide structured input to jobs.  IMHO we should remove the restriction.

Either way, we should clarify the text.  If we want to relax it, we need to either fix the JCR or replace with json-schema (resolving #142).

The json-schema validator in flux-core restricts attributes to strings.   Looks like the cpp libjobspec used in sched also has this restriction.  So those (and their tests) will require attention as well.

**Comment by grondo** [comment]
I'm trying to recall the use cases for these attributes -- as far as I recall

 * `attributes.user` was reserved for arbitrary user metadata which could be passed along in the jobspec and/or stored in the "permanent" job record. The use cases for that are pretty open ended, so it seems clear we wouldn't want to limit the values to strings only.

 * The main use case for `attributes.system` is as a conduit for user-selected optional system components, e.g. similar to Slurm spank plugins. In this case I can't think of cases where we would absolutely need non-string values, however, as shown in flux-framework/flux-core#2073 it might be useful to at least allow it for future flexibility.

I'm sure there are other use cases I'm missing, but even from these two examples we seem to be in agreement that the restriction should be removed. We have a nice way to extend our validation (at least conceptually) of submitted jobspec, so there isn't a compelling reason for the restriction IMO.

**Comment by garlick** [comment]
Closed by #173
