### ISSUE TITLE
RFC 14: define jobspec duration format

### ISSUE THREAD

**Issue by garlick** [flux-framework/rfc#175]
Peeling this off of #149 (document minimal jobspec).

RFC 14 does not really define the `duration` attribute in any detail.  It says:
> The value of the duration attribute is a string representing time span. The scheduler will make an effort to allocate the requested resources for the time specified in duration.

The jobspec valid inputs (from flux-core sharness test) are:
```
$ grep duration valid/*
valid/example1.yaml:    duration: 1 hour
valid/example2.yaml:    duration: 1 hour
valid/use_case_1.1.yaml:    duration: 1 hour
valid/use_case_1.2.yaml:    duration: 1 hour
valid/use_case_1.3.yaml:    duration: 1 hour
valid/use_case_1.4.yaml:    duration: 1 hour
valid/use_case_1.5.yaml:    duration: 4 hours
valid/use_case_1.6.yaml:    duration: 1 hour
valid/use_case_1.7.yaml:    duration: 1h
valid/use_case_2.1.yaml:    duration: 1 hour
valid/use_case_2.2.yaml:    duration: 1 hour
valid/use_case_2.3.yaml:    duration: 1 hour
valid/use_case_2.4.yaml:    duration: 1 hour
valid/use_case_2.5.yaml:    duration: 1 hour
valid/use_case_2.6.yaml:    duration: 1 hour
```
The json-schema simply requires
```json
"duration": { "type": "string" }
```

In #149, @grondo proposed
> Actually we could increase both ease of parsing and readability if we allowed duration to be a string with the same format as GNU sleep(1), i.e.
>
>> NUMBER[SUFFIX] - Duration in NUMBER seconds. SUFFIX may be 's' for seconds (the default), 'm' for minutes, 'h' for hours or 'd' for days. NUMBER may be an arbitrary floating point number.
> 
> Slurm-style duration as above is easily converted to this format, though for flux tools the sleep(1) syntax is much more user-friendly IMO.

Do we want to tighten up RFC 14 to _require_ this format?

**Comment by grondo** [comment]
I think that discussion was in the context of *minimal* v1 jobspec, not rfc 14 jobspec.

**Comment by grondo** [comment]
I'm not opposed to requiring a duration format for RFC 14, though. I just wasn't sure if that was required at this time, nor if the `NUMBER[SUFFIX]` duration would be sufficient long term.

On the other hand, there are a lot of other tools that take a duration currently, but only support floating-point seconds. I was thinking of enhancing all those commands to support the form above. Maybe we can make a short RFC and call this format "Flux Standard Duration:tm:", then say jobspec requires Flux Standard Duration?

**Comment by grondo** [comment]
After this morning's meeting it seemed like updating all jobspec duration values to strict number of seconds was going to be the best approach. Since it generated confusion to have a difference between minimal jobspec and canonical jobspec, I propose we update both. I have a pending change to RFC 14 in #177, and a corresponding PR in flux-core.

**Comment by SteVwonder** [comment]
Just to clarify, *minimal* jobspec requires duration in floating-point seconds, but the *canonical* jobspec will allow for any valid *Flux Standard Duration*?

**Comment by grondo** [comment]
> Just to clarify, minimal jobspec requires duration in floating-point seconds, but the canonical jobspec will allow for any valid Flux Standard Duration?

No, I think we updated canonical jobspec to *require* duration in floating-point seconds, on the premise that we want to optimize ease of parsing/reading canonical jobspec over human readability.

We added documentation of *Flux Standard Duration* only so that tools that take this format can refer to the rfc.
