### ISSUE TITLE
RFC 14: where to put job "options" e.g. as read by the shell and shell plugins?

### ISSUE THREAD

**Issue by grondo** [flux-framework/rfc#201]
Possibly related to the V1 jobspec being devloped in #189.

A spot in jobspec for generic "options" needs to be chosen. It seems like the de facto place for this kind of thing has become a key under `attributes.system`, as I think we've defined `attributes.user` as purely for non-flux related usage, so flux things shouldn't look there.

The straightforward approach would be to have the "shell" take `attributes.system.shell` namespace, e.g. `attributes.system.shell.verbose = true` could turn on the shell's verbose flag. Arbitrary shell plugins could claim a namespace under `attributes.system.shell` and grab options from there, e.g. `attributes.system.shell.output.filename = "flux-{{jobid}}.out"`.

Maybe we want to put these options one level further down to allow for future expansion, e.g. `attributes.system.shell.options.`. Maybe we want to be even more careful and use some kind of globally unique naming scheme (e.g. like starting with the domain name of the plugin originator)

Any thoughts? I'm inclined to start with `attributes.system.shell.options` and just a good neighbor policy to name your plugin's namespace uniquely if its options format conflicts with an existing option.

**Comment by SteVwonder** [comment]
> Any thoughts? I'm inclined to start with attributes.system.shell.options and just a good neighbor policy to name your plugin's namespace uniquely if its options format conflicts with an existing option.

I second that suggestion!  I think a globally unique name is overkill (at least for now).

**Comment by grondo** [comment]
I think we've settled on `attributes.system.shell.options`. Closing.
