### ISSUE TITLE
RFC 14: clarify and/or simplifiy command specification 

### ISSUE THREAD

**Issue by chu11** [flux-framework/rfc#213]
When reading the definition of a command:

`The value of the command key SHALL be a string OR list representing an executable and its arguments.`

I originally read this as "The command key SHALL be string OR list, each of which could be representing an executable and its arguments".  Presumably arguments in the string are separated by spaces.

but, seeing some code in `flux-core/shell`, it interprets this sentence more like: "the command key SHALL be a string with a single command OR a list representing an executable and its arguments".  In other words, commands with arguments must be in list form, strings are arrays of length one.

It need not matter, but it should be clarified which is the correct interpretation with code adjusted accordingly.

OR

perhaps things could be simplified.  Perhaps the command should always be a list?  As far as I can tell, it is only used as a list in the current `flux-core`.  Some examples would have to be updated as a result.

**Comment by grondo** [comment]
Currently a string is treated as a list of one entry.

It would probably simplify the parsing code if the `command` could always be assumed to be a list, passed directly to exec.

**Comment by chu11** [comment]
> It would probably simplify the parsing code if the command could always be assumed to be a list, passed directly to exec.

Sounds like a good idea to me.
