### ISSUE TITLE
RFC 14: add a 'bank' field to jobspec?

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/rfc#262]
I'm sorry in advance if this is not the right RFC to reference!

I opened an issue in [flux-framework/flux-core #3136](https://github.com/flux-framework/flux-core/issues/3136) that discussed some of the gaps when trying to create job usage reports. One of the fields needed is a `bank` field, a field that stores what bank the user charged their job against (filtering job records by bank was one of the features discussed with Ryan Day). @grondo left this feedback in that thread:

> We'll need to determine a spot where the group/account gets set in jobspec. Then you can pull it from there, or it may be important enough to add to job-info and perhaps broken out as a separate key in job-archive?
> We may want to open an issue on this in the rfc repo.

Does it make sense to place a `bank` field in jobspec? I assume that a `bank` would be an option passed in by the user when submitting a job, and it defaults to some bank if nothing is passed in:

```
$ flux mini submit --bank=this_specific_bank -n 1 hostname
```

From a flux-accounting perspective, I tried to think of ways to pull the same information directly from the flux-accounting database without needing to include it in jobspec. I first thought that a lookup could be performed with the username passed in to see which bank the user belongs in, but one issue that comes to mind is the possibility that a user belongs to multiple banks... so, would there instead to be a lookup in the flux-accounting database performed immediately after a job is submitted to validate which `bank` was specified?

**Comment by SteVwonder** [comment]
> Does it make sense to place a bank field in jobspec? I assume that a bank would be an option passed in by the user when submitting a job, and it defaults to some bank if nothing is passed in:

👍 Makes sense to me.  Maybe under `attributes.system.bank`?

**Comment by dongahn** [comment]
@cmoussa1: 

Please see how we add "queue" info into job spec:

https://github.com/flux-framework/flux-sched/blob/master/t/t1009-recovery-multiqueue.t#L29

At some point, we can take a deeper look at the scheduler-specific data schema like queue and bank. But for now, what @SteVwonder suggested makes sense to me.

**Comment by garlick** [comment]
Fixed by #420
