### ISSUE TITLE
Add commit style to RFC 7

### ISSUE THREAD

**Issue by garlick** [flux-framework/rfc#27]
@grondo listed some guidelines for commit formatting in flux-framework/flux-core#315

Perhaps RFC 7 should be renamed to _7/Flux Coding and Change Management Style Guide_ and be amended to include guidelines for well formed git commits?

**Comment by grondo** [comment]
Good idea. Another title could be *Flux Contributing Guide* or similar? Standard practice to cover these topics seems to be  a `CONTRIBUTING` file in the top level of the src tree...

**Comment by grondo** [comment]
Just noticed that if you place `CONTRIBUTING` or `CONTRIBUTING.md` in top level of your project, github will create a link to the file whenever someone creates a PR or Issue:

 https://github.com/blog/1184-contributing-guidelines

I'm thinking once we update RFC 7 we can make a standard `CONTRIBUTING.md` that links to this RFC and can be placed in the top level of any Flux Framework projects.

**Comment by grondo** [comment]
Reading back through [RFC 1](https://github.com/flux-framework/rfc/blob/master/spec_1.adoc) I noticed some of this is covered in very high detail in the C4.1. Still ok to add the commit message guidelines and more detail on creating "patches" to RFC 7, or would you rather enhance C4.1?

**Comment by garlick** [comment]
Lets amend C4.1 and keep RFC 7 focused on coding style then.  See PR #28.

**Comment by grondo** [comment]
I think this issue can be closed. I submitted an example `CONTRIBUTING.md` to flux-core that references the updated RFCs here...
