### ISSUE TITLE
rfc21: flux-restart name / description

### ISSUE THREAD

**Issue by chu11** [flux-framework/rfc#275]
re-reading rfc21

```
Flux-Restart Event

The job manager has restarted.

No context is defined for this event.
```

the description of the `flux-restart` event suggests that it should be logged everytime flux is restarted.  But it should really only be for when we transition from SCHED back to PRIORITY.  

I was going to write a PR to just add some clarifying information, but it made me ponder if the event name `flux-restart` should be re-considered?  `priority-invalidate` and `reload` were discussed in https://github.com/flux-framework/flux-core/issues/3311.  how about something like `priority-recalc`?

**Comment by garlick** [comment]
For now the intent was just to log it for jobs in SCHED, leaving the option open to log it for all active jobs in the future.

Maybe a comment in the code would suffice?
```
/* The flux-restart event is currently only posted to jobs in SCHED state
 * since that is the only state transition defined for the event in RFC21.
 * In the future, other transitions may be defined.
 */
```

**Comment by chu11** [comment]
ok sounds good
