### ISSUE TITLE
[idea] rfc21: support optional "restart" context keys to help indicate a restart happened

### ISSUE THREAD

**Issue by chu11** [flux-framework/rfc#276]
As I began thinking of tests to work on for flux core issue https://github.com/flux-framework/flux-core/issues/3345, I realized now that RFC21 allows cycles (https://github.com/flux-framework/rfc/pull/274), some `flux job wait-event` calls may no longer work for testing.  Like perhaps I want to wait for the second `priority` event to occur, not the first.

Obviously I can `flux job info <jobid> eventlog | grep <name> | wc -l ` to detect what I want, but sort of defeats the purpose of having `flux job wait-event`, especially when things can be racy.

I was thinking, we do have `flux job wait-event --match-context="KEY=VAL"`.  Perhaps there could be optional context info output to indicate a restart happened.  Hypothetically:

```
submit
depend
priority priority=100
flux-restart restart=1
priority priority=100 restart=1
```

**Comment by garlick** [comment]
Would it be more generally useful to add a --count option to wait-event?

**Comment by grondo** [comment]
> Would it be more generally useful to add a --count option to wait-event?

I like that!

**Comment by chu11** [comment]
oh haha!  I had considered a `--count` to be more intrusive / annoying, so I was looking for other ways.  But if you're ok with that, sounds good to me!
