### ISSUE TITLE
rfc 14: request resources per `X`, when `X` is unspecified

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/rfc#298]
Use case:

A user wants to request a certain amount of storage/memory per node, but doesn't specify how many nodes they want. Something like `count: 2 per-X` where `X` could be anything (slot, GPU, etc.) might be a flexible way to allow this. Alternatively maybe an entry could be made (in this case `node`) without a `count`.

**Comment by grondo** [comment]
This reminds me that RFC 14 resources support `min` and `max` as well as `count`. Would it work to have a `min: 1` or even `min: 0` for this case?

**Comment by jameshcorbett** [comment]
I think that would work! IIRC Stephen said that `min` doesn't have any effect right now but that's an issue for flux-sched and not here. I guess I will close this then.
