### ISSUE TITLE
C or C++ comments

### ISSUE THREAD

**Issue by lipari** [flux-framework/rfc#30]
Does anyone have an opinion for or against the use of the C++ style comments "//" in our C code?  Should we make a recommendation under the C coding style section of [RFC 7](https://github.com/flux-framework/rfc/blob/master/spec_7.adoc)?  Or should this be an option left up to the developer?

**Comment by grondo** [comment]
We adopted C99 which allows those `//` one line comments, so I think they're fine.

**Comment by lipari** [comment]
Since there were no further opinions, I'll close this issue.
