### ISSUE TITLE
finish documentation of Flux wire protocol

### ISSUE THREAD

**Issue by garlick** [flux-framework/rfc#344]
A slack discussion reminded me that we have gaps in our documentation of Flux's "wire protocol".  By that I mean how Flux messages are sent and received directly on a socket like the "local connector" (a UNIX domain socket)

What we have:

* [RFC 3](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_3.html) defines the Flux message format in terms of multi-frame messages (using zeromq terminology)
* [RFC 6](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_6.html) defines Flux RPCs in terms of Flux request and response messages

Doc gaps:

* [message encoding](https://github.com/flux-framework/flux-core/blob/master/src/common/libflux/message.c#L223), which used to be outsourced to zeromq
* [message framing for the local connector](https://github.com/flux-framework/flux-core/blob/master/src/common/librouter/sendfd.c), which has been stable for a long time but was never documented.

Ideally it should be possible to implement code for sending Flux RPCs wtih arbitrary (JSON or raw) payloads wtihout using libflux-core.so, in case someone wants to do a native implementation in some language instead of libflux-core bindings.  That might be useful, for example, when libflux-core's reactive programming model is not a good fit for a language's concurrency model.

**Comment by vsoch** [comment]
Ping @alecbcs!
