### ISSUE TITLE
rfc31: need to define an "always match" / "never match" constraint object

### ISSUE THREAD

**Issue by chu11** [flux-framework/rfc#376]
In rfc31 "not specifying" a constraint object would mean "match everything" or "there are no constraints".

But there may be circumstances we would like to define a constraint object that "matches everything" or indicates "there are no constraints".  For example, lets say we had the function:

`json_t *build_me_constraint_object (param1, param2, param3);`

This function could return NULL to indicate "no constraint object" given the inputs, but if it might be convenient if it could always return an object.

https://jsonlogic.com/ proposes that json `true` and `false` be defined for "always match" and "never match".  But given our use case, we feel this is not a good use in flux.

After some offline discussion with @grondo, we think defining an empty json object, i.e. `{}` might be very suitable for "no constraints" and "always matches".

But we do hit the issue of what is the "never matches" case?  I admit I'm not 100% sure.

Given my comments in #375, an alternate proposal might be:

"always match" :  `{}` or `{ "and": [] }` or `{ "or": [] }`.
"never match": `{ "not": [] }`

**Comment by chu11** [comment]
minor correction in what jsonLogic says:

```
Always and Never

Sometimes the rule you want to process is “Always” or “Never.” If the first parameter passed to jsonLogic is a non-object, non-associative-array, it is returned immediately.

//Always
jsonLogic.apply(true, data_will_be_ignored);
// true

//Never
jsonLogic.apply(false, i_wasnt_even_supposed_to_be_here);
// false
```

it's not that true/false means "true/false" its just that the code just processes what was passed in if it's not an object.

**Comment by grondo** [comment]
Keep in mind that RFC 31 is "inspired" by JsonLogic, not meant to be compatible or comply with JsonLogic.
Without thinking about too hard, it makes sense to have an empty constraint `{}` be legal and treated the same as no constraint, which would match anything.

For match nothing, `{"not": []}` works for me, though I do wonder if we could come up with something clearer.
