### ISSUE TITLE
RFC14,25: add preemptible-after attribute

### ISSUE THREAD

**Issue by grondo** [flux-framework/rfc#423]
In flux-framework/flux-core#5739 there is a proposal to add a flag to preemptible/standby jobs. A scheduler can then use this flag to determine if a job may be canceled to make way for a higher priority job. However, currently flags are not shared with the scheduler, which would have to read the `submit` event to get the flags.

We should consider adding flags to the alloc request (which contains most of the rest of the submit event context).

**Comment by garlick** [comment]
In #5378, @ryanday36 mentioned an alternate idea to a standby flag: allow a duration _range_ in jobspec, where a standby job would specify a min < max duration and the job would be eligible for preemption after the min duration expires.  For traditional standby, min = 0, but it would allow for a job to request to get a minimum amount of work done before preemption.  It seems like we discussed this and decided it was a better idea than the flag but I can't find anything to cite here.

A duration range would require an update to
- [RFC 14/Canonical Job Specification](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_14.html)
- [RFC 25/Job Specification Version 1](https://flux-framework.readthedocs.io/projects/flux-rfc/en/latest/spec_25.html)

Shall we change this issue from flag to duration range?

**Comment by grondo** [comment]
Yes, that's a good idea. I wonder if it would be easier to add an optional minimum duration instead turning duration into a range though...

**Comment by grondo** [comment]
BTW, I just recalled that when we discussed this proposal of a minimum duration one possible solution was to still use the preemptible flag, but to have the job-manager post the flag to the eventlog as soon as minimum runtime expired. We should explore if that makes sense, or if we leave it up to the scheduler to look for any minimum runtime and implement preemption internally without need of any kind of flags.

**Comment by grondo** [comment]
> Maybe `preemptible-after`?

Good suggestion!

**Comment by garlick** [comment]
Well, thinking about this a bit more, it seems like the scheduler will want to incorporate future preemptibility into its "plan", so I'm not sure how useful it is to know when a job becomes preemptible in real time?  Maybe it would be better to just have the scheduler raise a fatal exception on a job when it reaches that point in its schedule and skip the notification?

**Comment by garlick** [comment]
> Either way it doesn't seem like the flag is useful, so we can probably close this issue or change it to add the preemptible-after attribute, which is only supported by Fluxion.

Before we discard that idea completely we might want to try a little prototype of `preemptible-after` with `sched-simple`.  At minimum, we may find that some libschedutil support falls out of it that will save fluxion developers some work.  Like I dunno, a wake up timer when running jobs become preemptible since otherwise the scheduler might not have any other event to wake up on?

**Comment by grondo** [comment]
Does libschedutil examine jobspec? In any event, an experiment with sched-simple is a good idea.

Since sched-simple is not a planning scheduler, preemptible jobs would not have much effect if they are submitted behind a pending job. However, it could be used to test that submission of a high priority job kills off any existing preemptible jobs if that would allow the job to run. :shrug:
