### ISSUE TITLE
Requirement for Modeling Flow

### ISSUE THREAD

**Issue by lipari** [flux-framework/rfc#56]
From the beginning, we have identified the need for a flexible resource model that goes beyond the traditional nodes, cores, and memory resources.  With the creation of RFC’s [4](https://github.com/flux-framework/rfc/blob/master/spec_4.adoc) and [14](https://github.com/flux-framework/rfc/blob/master/spec_14.adoc), we have made good headway towards specifying just such a model.

The structure of that model is dominated by a hierarchical composite relationship.  This reflects the real-world physical composition as well as the hierarchy modeled in the Portable Hardware Locality (hwloc) project.  As we continue forward, we need to formalize the paths toward supporting extraneous relationships that are not currently captured by the physical hierarchy.  The two use cases of immediate concern are power and network communication, though there could be other relationships that arise someday.

The plans for supporting power and communication call for a new graph model that models flow.  In this model a resource, for example a compute node, could belong to not just its physical hierarchy but also a power distribution model as well as a network topology model.  This allows us to design scheduling algorithms focused specifically on scheduling flow and connectivity in addition to the physical resources.

This issue introduces the need to enhance or augment our existing RFC’s 4 and 14 to include the support for such flow models.

**Comment by dongahn** [comment]
This sounds great. Do we want to also use @SteVwonder's IO BW aware scheduling as a use case as well?

**Comment by lipari** [comment]
Yes indeed.

**Comment by dongahn** [comment]
BTW, one concrete discussion that can help push forward this dialogue would be #54 when you want to use BW or other link performance allocation as your constraints.  I think these two issues (resource specification and representation) kind of go together hand in hand. As you want to be able specify link quantities as your resource requirements and we want to be able to represent that in the scheduler's resource state. This is also well aligned w/ @StevWonder's next round of research for IO aware scheduling as we want to use BW awareness to make good scheduling decisions for burst buffer staging.

**Comment by dongahn** [comment]
I now have flexible ways to represent flow resources in the current flux resource model and I believe that I have generate enough discussions I'd need on this topic from @tpatki and @SteVwonder. Closing.
