### ISSUE TITLE
Does flux-devel@lists.lustre.org exist?

### ISSUE THREAD

**Issue by morrone** [flux-framework/rfc#57]
RFC spec_2.adoc mentions a flux-devel@lists.llnl.gov mailing lists.  Does that list really exist?  I could only find flux-discuss on lists.llnl.gov.

**Comment by garlick** [comment]
Nope, flux-discuss is all we have, and it's barely justified given how much we rely on github for communication.  Anyway, yes we should fix spec_2.  care to submit a PR? :-)

**Comment by grondo** [comment]
We were looking at moving discussion list offsite, any suggestions?

**Comment by garlick** [comment]
Public archives would be nice.  (Not possible with LISTSERV!!!!! which must be YELLED since it is like 50 years old before upper case was invented).

**Comment by morrone** [comment]
We used Dreamhost's mailman services for lustre.org and opensfs.org.  They are included in their cheapest shared-hosting option ($11/month, $120/1year, etc.).  I'm not sure what there is in the totally-free arena.
