### ISSUE TITLE
rfc14: Is jobspec YAML or not?

### ISSUE THREAD

**Issue by morrone** [flux-framework/rfc#85]
In reading the rfc14, I am left wondering if the jobspec is really YAML or not.  Some places seem to say that it is, but others say things like "domain specific language based on YAML".

I think it would be useful to decide that it really is written in YAML.  There are a number of benifits of doing that:

* Everyone that wants to work with jobspec can start with an off-the-shelf parser and focus more on content.
* We inherit other niceties from YAML such as:
** Comments
** Document markers (---), so we can easily have multiple jobspec in one file or stream
* We can document jobspec in standard YAML terminology, "X is a mapping"

Are there good reasons not to go that route?

**Comment by grondo** [comment]
@morrone, great comment and sadly I can't remember why we weren't willing to say jobspec is definitely YAML at the time.

At this point I'm inclined to agree with your assertion.

**Comment by garlick** [comment]
As I recall a "domain specific language based on YAML" would be valid YAML, and also valid in terms of domain requirements?  So an off the shelf YAML parser would still be useful.

One drawback of YAML is the defacto parser in C is [libyaml](https://github.com/yaml/libyaml) which has a pretty low level interface (as I recall).  This may be irrelevant if we never need to parse it in C, but if we do it's not all that easy.

A thought recently expressed by @trws (correct me if I'm putting words in your mouth Tom) was that maybe in the interest of getting this done soon, the _canonical_ (internal)  jobspec could just be JSON.  I think he felt that everything that is expressible in YAML is expressible in JSON. and that the main utility of YAML was the little bells and whistles that allow you to make a human readable domain specific language out of it.

**Comment by morrone** [comment]
Well, that would explain when there is a description section written in JSON description language. :)

I don't know...I think we need to make some decisions quick about which way we are going on this.  I think we should have _one_ written format, and I don't care if it is JSON or YAML.  But any other helpful generators for "non-canonical" formats should just be dropped from our documentation.  Instead we can say something simple like: "We expect that third parties will write their own scripts to make it easier to generate canonical jobspecs, or to translate from other formats."

I think we will have our hands full for the forseable future doing the jobspec, and then another spec for serializing specific resource allocations, and who knows what else.  I don't think we should have more than one jobspec from the get-go.

**Comment by garlick** [comment]
I think that was the group consensus.  The "canoncial jobspec" was an attempt to get to the heart of the matter and leave expressiveness enhancements for later.

**Comment by morrone** [comment]
It's YAML based. :)
