### ISSUE TITLE
RFC14: Replace "walltime" with scheduler attributes

### ISSUE THREAD

**Issue by morrone** [flux-framework/rfc#90]
I would like to propose that we remove the top-level "walltime" item from the jobspec.

I think that the current time constraints can probably be expressed as generic key-value attributes.  For instance, perhaps these examples:

  walltime-estimate=12h
  walltime-minimum-required=4h

I think it makes sense to use attributes, because different schedulers might have any number of other constraints/features that can be expressed.  For instance:

  restartable=yes
  preemptable=yes
  importance=8

So perhaps _all_ of the scheduler-related should just be key-value attributes to make them easily extensible by various schedulers in the future, without needed to redefine the spec for each scheduler.

If that seems reasonable, then there are a couple of ways to go about this.

First, we could simply fold the scheduler attributes into the top-level "attrs" item that is already defined in rfc14.

As I see it, the major drawback is in error reporting.  If someone misspells a key, flux will likely silently ignore that key, assuming that it is a random key of meaning to the user or application rather than one intended for the flux scheduler.

Second option: Introduce a new mapping named something like "scheduler_attrs".  We might enforce that all specified keys must be recongnized by the current scheduler.  Or perhaps only generate warnings for unrecognized keys, which would then allow the user to use the same jobspec for both more complicated scheduler, and for a simpler scheduler that doesn't support all of the options from the complicated scheduler.

I think I like the idea of having a separate "scheduler_attrs", and only warn about unsupported keys.

In the rfc14, we should also list common scheduler_attrs keys and require that schedulers use the same keys for the same purpose when at all possible.

**Comment by dongahn** [comment]
Putting scheduler-capability-related specification into "scheduler_attrs" makes sense to me. On a related topic, we may need a general way to do a general compatibility or capability check between a jobspec and the scheduler instance? What if a jobspec has type="node"; yet the scheduler instance only does "core" level scheduling?

BTW, what is "importance?" priority?

**Comment by grondo** [comment]
What is the benefit of top-level `scheduler_attrs` vs `attrs.scheduler`? I like folding sched-specific attributes this way because I'm sure there will be other generic job attributes that will need to be lumped by subsystem, and for some reason I like collecting these under `attrs` rather than requiring generic `foosystem_attrs` added at the top level. However, I may be missing some benefit of putting these specific attributes at the top level.

> What if a jobspec has type="node"; yet the scheduler instance only does "core" level scheduling?

We've proposed the idea of "feasibility checks" on job submission. Scheduler and other subsystems that have specific requirements should be able to register hooks into the feasibility check stack.

**Comment by dongahn** [comment]
> We've proposed the idea of "feasibility checks" on job submission. Scheduler and other subsystems that have specific requirements should be able to register hooks into the feasibility check stack.

Maybe, we can design a category of requirements that a scheduler instance satisfies and rejects a jobspec that cannot be satisfied by that requirements. This can be one layer in the feasibility stack. Sort of like a  type checker; (or concept checker in the case of C++ template parameters).

**Comment by lipari** [comment]
Regarding the title of the issue, I think of a wall request as fundamentally independent of attributes.  Hence, I would argue to maintain the distinction RFC 14 currently makes between wall time and attributes.

Regarding the dangers of typos in specifying attributes, I would hope a mis-typed job submit request would be rejected at submit time.  This would immediately alert the user to the fact that they need to fix their submit request.

Regarding the need for two categories of keys, those that must be spelled correctly and those that may only apply to certain schedulers, then I support @dongahn 's idea of creating two categories of attributes:  those that must be spelled correctly and those that are suggestions that may only apply to certain schedulers or scheduling scenarios.

**Comment by morrone** [comment]
> What is the benefit of top-level scheduler_attrs vs attrs.scheduler

@grondo, I am not clear on what you mean by "attrs.scheduler".  Oh!  Are suggesting that certain keys in the "attrs" mapping could themselves be mappings?  I like that.  Maybe just to stay consistent (in a way), we redefine "attrs" to be a "mapping of mappings".  Then perhaps there is a "user" mapping for any random key/values that users choose to create.

So an attrs section might look like this:

 attrs:
     scheduler:
         estimated-time: 12h
         minimal-time: 4h
         preemptable: yes
         reastartable: no
     user:
         graph-resolution: superfine
         phase: 3
 

> On a related topic, we may need a general way to do a general compatibility or capability check between a jobspec and the scheduler instance?

If we want the checker to be a stand-alone component rather than an API that the scheduler plugin offers, then we would need to create another form of API where the stand-alone checker queries the scheduler for its capabilities at start-up, so it is able to enforce them.  It is not entirely clear to me that the latter is an improvement over the former, but I don't really have a strong opinion.

> BTW, what is "importance?" priority?

It was a loose idea from a paper [a paper ](http://journals.sagepub.com/doi/pdf/10.1177/1094342006068414) that Jim shared with me.  Basically, a user might express to the scheduler what their personal priority is for the job (distinct from the global job priority that the scheduler may be calculating).  Then a user that has a milestone in 2 days might set the importance/personal-priority to very high, and a user that doesn't need the data for a month might set the importance/personal-priority low.  I was wondering if we might be able to integrate that concept with our local bank concept to allow users to drain their bank faster or slower as their needs demand.

Certainly a digression in the context of this ticket, but thoughts like that drove me to document the idea of making scheduler options a bit more generic and extensible without necessarily changing jobspec versions in the future.

> I think of a wall request as fundamentally independent of attributes. 

@lipari, could you please elaborate?  I don't see the time constraint as significantly different than an other number of constraints that the user might want to relay to the scheduler.  Perhaps it will be the most frequently used contraint, but other than frequency of use I don't see why it could not be stored in the same area of the jobspec.

**Comment by grondo** [comment]
>  Oh! Are suggesting that certain keys in the "attrs" mapping could themselves be mappings? I like that. Maybe just to stay consistent (in a way), we redefine "attrs" to be a "mapping of mappings". Then perhaps there is a "user" mapping for any random key/values that users choose to create.

Yes, I was suggesting something like what you proposed. I like the idea of requiring it to be a mapping of mappings.

**Comment by lipari** [comment]
>>   I think of a wall request as fundamentally independent of attributes.
> @lipari, could you please elaborate? I don't see the time constraint as significantly different than an other number of constraints that the user might want to relay to the scheduler.

In the most general terms, it is what you want vs. (when and) how long you want it.

Example:  two all beef patties, special sauce, lettuce, cheese, pickles, onions on a sesame seed bun
 - for 5 minutes.

**Comment by garlick** [comment]
Job rejected, errno = EWTHATSGROSS

**Comment by morrone** [comment]
> In the most general terms, it is what you want vs. (when and) how long you want it.

"what you want" would seem to translate into what is found in the Resources section of the jobspec.  "how long you want it" seems like just one of many kinds of abstract contraints that would not appear in the Resources section.

More abstract concepts like whether a job is preemptable (standby jobs?) or restartable, or providing a user's personal priority seem to match the abstractness of time constraints to me.

**Comment by trws** [comment]
I'd agree with that interpretation.  The real reasoning, at least from my end, for having walltime and some of that in the task explicitly rather than in attributes was to have it be something we would be sure to treat as a structure member once it's deserialized and to make it less painful for a user to specify.  Now that I think about it, especially given that the user probably wont write this version directly, that's not a great reason to do it...
